import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar/navbar'
import ThreeD from '../Components/Canvas/threeD'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <Navbar/>
      </nav>
      <main >
        < ThreeD/>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
