import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar/navbar'
import ThreeD from '../Components/Canvas/threeD'
import Cardcontainer from '../Page Components/Home/card-container'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <Navbar/>
      </nav>
      <main>
      <Cardcontainer/>
      </main>
      <footer>
      </footer>
    </div>
  )
}

export default Home
